export const CasesItems = [
    { className: 'CasesSection__item-Ctitle',
      classImg: 'CasesSection__item-img',
      text: 'Данная компания прекрасно знает свое дело, она не только создала нам сайт с нуля, а также занимается его продвижением.',
      title: 'Создание сайтов.',
      classDat:'CasesSection__item-dat',
      dat: '12.06.2019',
      img: 'images/image11.jpg',
      alt: 'one'
    },
    { className: 'CasesSection__item-title',
      classImg: 'CasesSection__item-img',
      title: 'Разработка дизайна.',
      classDat:'CasesSection__item-dat',
      img: 'images/image22.jpg',
      alt: 'two'
    },
    { className: 'CasesSection__item-Btitle',
      classImg: 'CasesSection__item-Nimg',
      title: 'Поддержка сайтов.',
      classDat:'CasesSection__item-Cdat',
      dat: '21.02.2020',
      img: 'images/image33.jpg',
      alt: 'three'
    },
    { className: 'CasesSection__item-Btitle',
      classImg: 'CasesSection__item-Nimg',
      title: 'Накрутка ботов.',
      classDat:'CasesSection__item-Cdat',
      dat: '14.11.2021',
      img: 'images/image44.jpg',
      alt: 'four'
    },
    { className: 'CasesSection__item-Ctitle',
      classImg: 'CasesSection__item-img',
      text: 'Отличная работа и любая помощь.',
      classDat:'CasesSection__item-dat',
      dat: '16.12.2021',
      title: 'Разработка и последующая поддержка проектов',
      img: 'images/image55.jpg',
      alt: 'five'
    },
    { className: 'CasesSection__item-title',
      classImg: 'CasesSection__item-img',
      title: 'Создание баз данных.',
      classDat:'CasesSection__item-dat',
      img: 'images/image66.jpg',
      alt: 'six'
    },
    { className: 'CasesSection__item-Btitle',
      classImg: 'CasesSection__item-Nimg',
      title: 'Настройка сайтов.',
      classDat:'CasesSection__item-Cdat',
      dat: '22.04.2019',
      img: 'images/image77.jpg',
      alt: 'seven'
    },
  ];